# General
allow_remote_control socket
listen_on unix:/tmp/$USER-kitty.sock
confirm_os_window_close 0
remember_window_position yes
enabled_layouts Splits

# Font and cursor
font_family JetBrainsMono Nerd Font Mono
cursor_shape beam
cursor_blink_interval 0.5

# Window appearance
background_opacity 0.95
window_padding_width 10 8 0 8
enable_audio_bell no
mouse_hide_wait -1
scrollback_lines 10000

# Tabs
tab_switch_strategy previous
tab_bar_edge top
tab_bar_style powerline
tab_powerline_style slanted
tab_bar_min_tabs 2
tab_bar_filter session:~
tab_title_template "{index}"
tab_title_max_length 3
active_tab_font_style bold
inactive_tab_font_style normal

# Misc
copy_on_select clipboard
clear_selection_on_clipboard_loss yes
shell_integration enabled
clear_all_shortcuts yes

# BEGIN_KITTY_THEME
# Tokyo Night
include current-theme.conf
# END_KITTY_THEME

include ${KITTY_OS}.conf
