# Options
hide_window_decorations titlebar-only
macos_option_as_alt both
font_size 13.0

# Hints https://sw.kovidgoyal.net/kitty/kittens/hints
map cmd+u kitten hints --type url
map cmd+g kitten hints --type=linenum --linenum-action=self v +{line} {path}
# Copy instead
# map cmd+g kitten hints --type path --program @

# App and window management
map shift+cmd+w quit
map cmd+w close_window
map cmd+t new_tab_with_cwd
map cmd+n new_os_window
map cmd+r set_tab_title
map shift+cmd+, load_config_file
map cmd+, edit_config_file
map cmd+d launch --cwd=current --location=vsplit
map shift+cmd+d launch --cwd=current --location=hsplit
map cmd+f search_scrollback
map alt+equal set_background_opacity +0.05
map alt+minus set_background_opacity -0.05
map alt+0 set_background_opacity 0.9

# Tab navigation
map shift+cmd+[ move_tab_backward
map shift+cmd+] move_tab_forward
map cmd+[ previous_tab
map cmd+] next_tab
map cmd+1 goto_tab 1
map cmd+2 goto_tab 2
map cmd+3 goto_tab 3
map cmd+4 goto_tab 4
map cmd+5 goto_tab 5

# Pane navigation
map cmd+h neighboring_window left
map cmd+l neighboring_window right
map cmd+k neighboring_window up
map cmd+j neighboring_window down

# Pane movement
map shift+cmd+h move_window left
map shift+cmd+l move_window right
map shift+cmd+k move_window up
map shift+cmd+j move_window down

# Pane resizing
map ctrl+cmd+h resize_window narrower 2
map ctrl+cmd+l resize_window wider 2
map ctrl+cmd+k resize_window taller 2
map ctrl+cmd+j resize_window shorter 2

# Clipboard
map cmd+c copy_to_clipboard
map cmd+v paste_from_clipboard

# Utility shortcuts
map cmd+equal change_font_size all +2.0
map cmd+minus change_font_size all -2.0
map cmd+0 change_font_size all 0
map ctrl+cmd+, debug_config
map cmd+p command_palette

# Sessions
map shift+cmd+s save_as_session --use-foreground-process --base-dir ~/.config/kitty/sessions
map shift+cmd+c close_session
map cmd+/ goto_session ./sessions
