notARepository: "quit"
promptToReturnFromSubprocess: false
git:
  pagers:
    - pager: delta --paging=never -n --hyperlinks --hyperlinks-file-link-format="lazygit-edit://{path}:{line}" --file-style="omit"
os:
  editpreset: nvim
gui:
  sidePanelWidth: 0.2
  wrapLinesInStagingView: true
  useHunkModeInStagingView: true
  skipDiscardChangeWarning: true
  showBottomLine: false
  nerdFontsVersion: "3"
  border: rounded
  theme:
    unstagedChangesColor:
      - "#db4b4b"
    selectedLineBgColor:
      - "#283457"
    searchingActiveBorderColor:
      - "#ff9e64"
      - "bold"
    optionsTextColor:
      - "#7aa2f7"
    inactiveBorderColor:
      - "#7aa2f7"
    defaultFgColor:
      - "#c0caf5"
    cherryPickedCommitFgColor:
      - "#7aa2f7"
    cherryPickedCommitBgColor:
      - "#bb9af7"
    activeBorderColor:
      - "#ff9e64"
      - "bold"
